### ISSUE TITLE
Nuget Package Install Error (LeaderAnalytics.Caching)

### ISSUE THREAD

**Issue by dbettin** [leaderanalytics/Vyntix.Fred.FredClient#1]
Thanks for this great project.  

I am running into the following issue trying to install the nuget.

When I run `dotnet add [myproject.csproj] package LeaderAnalytics.Vyntix.Fred.FredClient --version 1.0.14-beta.1`,  I receive the following error message:

> error: NU1102: Unable to find package LeaderAnalytics.Caching with version (>= 1.0.15)
error:   - Found 3 version(s) in nuget.org [ Nearest version: 0.0.30 ]
error: Package 'LeaderAnalytics.Vyntix.Fred.FredClient' is incompatible with 'all' frameworks in project

**Comment by leaderanalytics** [comment]
Looks like the build for Caching is not working.   Fixing it now.

**Comment by leaderanalytics** [comment]
You should be good to go Dave.  Please try:
`dotnet add consoleapp1.csproj package LeaderAnalytics.Vyntix.Fred.FredClient --version 1.0.15-beta.1`
